"""add technical staff to user model

Revision ID: 5b680a8bdf7b
Revises: fba54cd0a557
Create Date: 2024-05-06 14:06:36.486101

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils 


# revision identifiers, used by Alembic.
revision = '5b680a8bdf7b'
down_revision = 'fba54cd0a557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_technical_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_technical_staff')
    # ### end Alembic commands ###
