"""new models

Revision ID: c254c640aa52
Revises: e44871bbe6e7
Create Date: 2024-03-30 08:26:50.714423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils
from app.models.issue import IStatusEnum, IIssueType
from app.models.public_area import AreaEnum


# revision identifiers, used by Alembic.
revision = 'c254c640aa52'
down_revision = 'e44871bbe6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_area',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('area_type', sqlalchemy_utils.types.choice.ChoiceType(AreaEnum), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('issue_type', sqlalchemy_utils.types.choice.ChoiceType(IIssueType), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(IStatusEnum), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laundry_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laundry_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laundry_id'], ['laundry.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_area_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_area_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['public_area_id'], ['public_area.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_area_schedule')
    op.drop_table('laundry_schedule')
    op.drop_table('schedule')
    op.drop_table('issue')
    op.drop_table('public_area')
    # ### end Alembic commands ###
