"""laundry

Revision ID: e44871bbe6e7
Revises: e2412789c190
Create Date: 2024-03-29 17:04:45.236554

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e44871bbe6e7'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laundry',
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('washing_machine_number', sa.Integer(), nullable=False),
    sa.Column('is_busy', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laundry')
    # ### end Alembic commands ###
