"""delete completed at

Revision ID: fba54cd0a557
Revises: c254c640aa52
Create Date: 2024-03-30 11:18:14.805501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fba54cd0a557'
down_revision = 'c254c640aa52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'completed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
